name: Rust

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: sudo apt-get install libssl-dev pkg-config -y

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose --release

    - uses: softprops/action-gh-release@v1
      name: Create a release
      with:
        fail_on_unmatched_files: true
        files: target/release/daily-wallpaper
