name: Rust

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release

    - uses: softprops/action-gh-release@v1
      name: Create a release
      with:
        fail_on_unmatched_files: true
        files: target/release/daily-wallpaper
